
# Šaltinių sąrašas

<div id="refs"></div>

# A priedas {-}
\renewcommand{\thetable}{A.\arabic{table}}
\setcounter{table}{0}                    

\renewcommand{\thefigure}{A.\arabic{figure}}
\setcounter{figure}{0}

```{r, fig.height=4, fig.width=12, fig.cap='Sesijos metu aplankytų puslapių skaičiaus pasiskirtymas kiekviename puslapio tipui'}
# BounceRates ir ExitRates pakylimas ant 0.20 keistai atrodo

numeric_cols <- c("Administrative", "Informational", "ProductRelated")

df_long <- df %>%
  pivot_longer(
    cols = all_of(numeric_cols),
    names_to = "Variable",
    values_to = "Value"
  )

ggplot(df_long, aes(x = Value)) +
  geom_histogram(bins = 30, fill = "#2C7FB8", color = "white") +
  facet_wrap(~Variable, scales = "free", ncol = 3) +
  labs(
    x = "Reikšmė",
    y = "Dažnis"
  ) +
  theme_minimal(base_size = 20)
```


```{r}
make_cross_table(df, "VisitorType")
make_cross_table(df, "Region")
make_cross_table(df, "Weekend")
make_cross_table(df, "Month")
```

# B priedas {-}
## DI naudojimas
Naudotas Google Gemini 3 Flash Preview, kad patikrinti ar surašyti
uždaviniai nėra etapai. Taip pat lentelėse, grafikuose pakeisti
taškus į kablelius, kad būtų lietuviškas formatavimas.
