# Išvados

Remiantis atlikta analize, logistinės regresijos modelis geriausiai klasifikuoja internetinės parduotuvės sesijų pelningumą, įvertinus modelio tikslumą, AUC reikšmę bei F1 matą. Nustatyta, kad „Probit“ modelio gebėjimas prognozuoti, ar sesija pasibaigs užsakymu, yra panašus į logistinės regresijos rezultatus: „Probit“ modelio F1 matas siekia 0,64, o „Logit“ – 0,65. Tuo tarpu „Cloglog“ modelis šiai klasifikavimo užduočiai nėra tinkamas, kadangi jo klasifikavimo tikslumas yra mažesnis nei dominuojančios klasės dalis duomenyse. Tyrimo metu pastebėta, kad Joudono indekso metodu optimizuotas klasifikavimo slenkstis nebuvo efektyvus – jis nepagerino nei modelio tikslumo, nei F1 mato, todėl jo taikymas šiuo atveju nėra tikslingas. Analizuojant kintamųjų įtaką, išaiškėjo, kad vartotojo operacinė sistema, regionas ir naudojama naršyklė yra statistiškai reikšmingi veiksniai prognozuojant sesijos pelningumą. Taip pat itin svarbios pasirodė „Google Analytics“ pateikiamos elgsenos metrikos – „Exit Rate“ ir „Page Values“, kurios turi tiesioginę įtaką galutiniam sesijos rezultatui.

# Praktinė nauda

Galėdami iš anksto nustatyti, kieno sesija bus nepelninga (nebus įvykdytas nei vienas
užsakymas), galima nustatyti į kuriuos naudotojus reikėtų atsižvelgti labiausiai,
tobulinant katalogą, svetainę ar strategiją.
Taip pat, nustatytdami kokie faktoriai neigiamai įtakoja sesijos pelningumo tikimybę, 
galima nustatyti kokios katalogo dalys ar kokie rinkos segmentai yra probleminiai,
kur galima pasitempti ir patobulinti strategiją.

\pagebreak